name: Squash Commits

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  squash_commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Squash commits
      run: |
        git reset --soft $(git rev-list --max-parents=0 HEAD)
        git commit --amend -m "update blacklist"

    - name: Force push the changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin HEAD --force
